### ISSUE TITLE
Use ActionSheetIOS on iOS

### ISSUE THREAD

**Issue by dave-irvine** [danielweinmann/react-native-controlled-picker#2]
So your react-native-picker-dropdown component very nicely uses ActionSheetIOS when on iOS, which is great and makes everything look very native, but it looks like you've gone in a different direction on this component.

Is there a reason why? Could this be configurable so we can use ActionSheetIOS if we want?

**Comment by danielweinmann** [comment]
The reason is that when you open an `ActionSheetIOS` you cannot close it programmatically. And the goal for this component is to be able to control it from the outside.

I always use `redux` + `redux-form` + [react-native-stateless-form](https://github.com/danielweinmann/react-native-stateless-form) to create a good form experience. And for that, I need to control the components from the outside.

**Comment by danielweinmann** [comment]
BTW, right now the documentation for `react-native-stateless-form` is outdated. I'm going to update it real soon when I add an `InlinePicker` component there.

If you decide to try it out, please create issues there and I'll gladly help you.
